export const PERMISSIONS_ENUM = {
  APPOINTMENT: {
    VIEW: "appointment.view",
    VIEW_OWN: "appointment.view_own",
    CREATE: "appointment.create",
    CREATE_OWN: "appointment.create_own",
    EDIT: "appointment.edit",
    CANCEL: "appointment.cancel",
    CANCEL_OWN: "appointment.cancel_own",
    DELETE: "appointment.delete",
  },
  SCHEDULE: {
    VIEW: "schedule.view",
    VIEW_AVAILABLE: "schedule.view_available",
    CREATE: "schedule.create",
    EDIT: "schedule.edit",
    DELETE: "schedule.delete",
    BLOCK: "schedule.block",
  },
  DOCTOR: {
    VIEW: "doctor.view",
    CREATE: "doctor.create",
    EDIT: "doctor.edit",
    DELETE: "doctor.delete",
    ASSIGN: "doctor.assign",
  },
  PATIENT: {
    VIEW: "patient.view",
    CREATE: "patient.create",
    EDIT: "patient.edit",
    DELETE: "patient.delete",
    VIEW_RECORDS: "patient.view_records",
  },
  BRANCH: {
    VIEW: "branch.view",
    CREATE: "branch.create",
    EDIT: "branch.edit",
    DELETE: "branch.delete",
    MANAGE_STAFF: "branch.manage_staff",
    MANAGE_SERVICES: "branch.manage_services",
  },
  SERVICE: {
    VIEW: "service.view",
    CREATE: "service.create",
    EDIT: "service.edit",
    DELETE: "service.delete",
  },
  LAB: {
    VIEW: "lab.view",
    CREATE: "lab.create",
    EDIT: "lab.edit",
    DELETE: "lab.delete",
    UPDATE_RESULT: "lab.update_result",
  },
  USER: {
    VIEW: "user.view",
    CREATE: "user.create",
    EDIT: "user.edit",
    DELETE: "user.delete",
    MANAGE_ROLES: "user.manage_roles",
  },
  ROLE: {
    VIEW: "role.view",
    CREATE: "role.create",
    EDIT: "role.edit",
    DELETE: "role.delete",
  },
  ANALYTICS: {
    VIEW_ALL: "analytics.view_all",
    BRANCH: "analytics.branch",
    REVENUE: "analytics.revenue",
    EXPORT: "analytics.export",
  },
  PROFILE: {
    VIEW: "profile.view",
    EDIT: "profile.edit",
  },
  SETTINGS: {
    VIEW: "settings.view",
    EDIT: "settings.edit",
    BRANDING: "settings.branding",
  },
} as const;
